### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [johnrambow/william-dean-howells_the-rise-of-silas-lapham#1]
- [ ] The worth while commit should be reverted; Alex has been asked about it several times, and always says leave it.
- [ ] Semanticate adds an "eoc" in chapter 21 that should be accepted.
- [ ] Separating the salutations in chapter 24 into a separate line is unnecessary; they can just be `<span>s` on the text. And, with a comma em-dash combination, it is the comma we get rid of, not the em-dash. (Typogrify should have done that, actually.)
- [ ] "Joshua Whitcomb" was just a sketch; the play was _The Old Homestead_. And the play didn't come out until the year the book was published, making it unlikely the play is being referred to. Since it's just a sketch, it should probably be in quotes (like other shorter works) rather than italics.
- [ ] The label in chapter 1 should be `<b>`; `<strong>` is reserved for strong emphasis (see [SEMoS 8.2.3](https://standardebooks.org/manual/1.7.3/single-page#8.2.3)), but here it is just formatting. Also, it should be titlecase, The Persis Brand.
- [ ] There is a "N.L.f. 1835⁠—S.L.t. 1855" in chapter 1 that is unsemanticated.
- [ ] There is a gold-mine and goldmine in chapter 1 that `find-mismatched-dashes` didn't catch because the first one is emphasized, i.e. _gold_-mine. Since at least one has to be changed anyway, and M-W says it's gold mine, then both should be corrected to that. (Editorial, of course.)

**Comment by johnrambow** [comment]
Hi Vince, OK, I think everything should be dealt with now. Thank you.
